version: '3.5'

services:
  web:
    restart: always
    ports:
      - 5000:5000
    environment:
      - NAME
    container_name: bingo_web

networks:
  default:
    external:
      name: spine_ext
