version: '3.9'

services:
  bingosvc:
    restart: always
    ports:
      - 5000:5000
    environment:
      - NAME
    container_name: bingo

networks:
  default:
    external:
      name: spine_ext
